/**
 * Shared recipe discovery and summarising.
 *
 * Recipes live in a tree, not a flat directory: the upstream 3x/4x/8x cluster
 * recipes keep their subdirectories so the topology they need is visible from
 * the path. Everything that walks `recipes/` goes through here so the
 * validator, the inventory and the publisher always see the same set of files
 * and read the same fields out of them.
 */

import { readFileSync, readdirSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { parseYaml } from './yaml.mjs';

/** Generated by the publisher, never itself a recipe. */
const NOT_A_RECIPE = new Set(['ds.manifest.yaml', 'index.yaml']);

/** Every `*.yaml` / `*.yml` under `dir`, recursively, in stable order. */
export function findRecipes(dir) {
  const out = [];
  const entries = readdirSync(dir, { withFileTypes: true }).sort((a, b) =>
    a.name.localeCompare(b.name)
  );
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...findRecipes(full));
    else if (/\.ya?ml$/.test(entry.name) && !NOT_A_RECIPE.has(entry.name)) out.push(full);
  }
  return out;
}

/** Read and parse one recipe file. */
export function readRecipe(path) {
  return parseYaml(readFileSync(path, 'utf-8'));
}

/** The declared recipe version; absent means v1. */
export function recipeVersion(data) {
  return data.recipe_version === undefined || data.recipe_version === null
    ? '1'
    : String(data.recipe_version);
}

/**
 * Engine names a recipe supports, preferred engine first.
 *
 * A v1 recipe is a vLLM command template and so runs on vLLM alone. A v2
 * recipe runs on the engines it lists under `engines`; `engine` only names
 * which of them is the default, except when it is the sole signal.
 */
export function recipeEngines(data) {
  if (recipeVersion(data) !== '2') return ['vllm'];
  const listed = Object.keys(data.engines ?? {}).sort();
  const preferred = data.engine ? String(data.engine) : null;
  if (!preferred) return listed;
  return [preferred, ...listed.filter((name) => name !== preferred)];
}

/**
 * The container image a recipe runs in.
 *
 * v1 states it outright. v2 states it per engine, so this reports the image
 * of the preferred engine — which is what the control plane's recipe list
 * shows in its `container` column.
 */
export function recipeImage(data) {
  if (recipeVersion(data) !== '2') return data.container ?? '';
  const engines = data.engines ?? {};
  for (const name of recipeEngines(data)) {
    const image = engines[name]?.image;
    if (image) return String(image);
  }
  return '';
}

/** Topology constraints, flattened; v1 carries them at the top level. */
export function recipeConstraints(data) {
  if (recipeVersion(data) !== '2') {
    return {
      solo_only: data.solo_only ?? false,
      cluster_only: data.cluster_only ?? false,
      min_nodes: null,
    };
  }
  const c = data.constraints ?? {};
  return {
    solo_only: c.solo_only ?? false,
    cluster_only: c.cluster_only ?? false,
    min_nodes: c.min_nodes ?? null,
  };
}

/**
 * What a recipe serves: `chat`, `embedding`, `image`, `video` or `speech`.
 *
 * Absent means chat, and so does every v1 recipe: upstream's format has no
 * such field and its command is a verbatim vLLM line, so the schema pins v1
 * to chat. Reported for every recipe, chat included, so a reader of the index
 * never has to know the default.
 */
export function recipeServes(data) {
  if (recipeVersion(data) !== '2') return 'chat';
  return data.serves ? String(data.serves) : 'chat';
}

/**
 * The artifact name for a recipe, derived from its path below `recipes/`.
 *
 * Not from the basename alone: three different recipes are called
 * `qwen3.5-397b-int4-autoround.yaml` (root, 3x and 4x), so the directory has
 * to survive into the name. `/` becomes `-`, which keeps the result a single
 * valid OCI path component.
 */
export function artifactName(relPath) {
  return relPath
    .split(sep)
    .join('/')
    .replace(/\.ya?ml$/, '')
    .split('/')
    .join('-')
    .toLowerCase();
}

/** Path of a recipe relative to the recipes directory, with `/` separators. */
export function recipePath(recipesDir, file) {
  return relative(recipesDir, file).split(sep).join('/');
}

/**
 * Everything the control plane's UI reads about a recipe, in one object.
 * Throws when a required field for the recipe's version is missing.
 */
export function summarise(data, relPath) {
  const version = recipeVersion(data);
  const required = version === '2' ? ['name', 'model'] : ['name', 'container', 'command'];
  const missing = required.filter((key) => !data[key]);
  if (missing.length) {
    throw new Error(`v${version} recipe is missing required field(s): ${missing.join(', ')}`);
  }
  const constraints = recipeConstraints(data);
  return {
    name: String(data.name),
    artifactName: artifactName(relPath),
    container: recipeImage(data),
    model: data.model ?? '',
    description: data.description ?? '',
    recipe_version: version,
    engines: recipeEngines(data),
    solo_only: constraints.solo_only,
    cluster_only: constraints.cluster_only,
    min_nodes: constraints.min_nodes,
    serves: recipeServes(data),
    path: relPath,
  };
}
